### ISSUE TITLE
create-react-app proxy not working

### ISSUE THREAD

**Issue by rohan-paul** [rohan-paul/chainable-dropdown-list#1]
In my .client/package.json I have the following 

```
"proxy": {
    "/": {
      "target": "http://localhost:5000/",
      "secure": false
    }
```
But in my app.js axios requst is not working if I just put like below

``axios.get('/')``

I have to put the full url - ``axios.get('http://localhost:5000/')``

**Comment by niinpatel** [comment]
I'm facing the same issue. Found any solution for this?

**Comment by rohan-paul** [comment]
Resolved it by doing the below in ``server.js``

``app.use('/api', car);`` 

And in ..src/App.js the below

``axios.get('/api')``

**Comment by niinpatel** [comment]
Oh yeah! I figured that too!
